spring:
  flyway:
    locations: classpath:db/migration,classpath:db/migration-prod

app:
  jwt:
    secure-cookie: ${JWT_SECURE_COOKIE:true}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://biblioteca.example.com}